/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetorpg;

import ferramentas.CaixaDeDialogo;
import modelos.Personagem;

/**
 *
 * @author Jonas
 */
public class TelaPrincipal extends javax.swing.JFrame {

    Personagem personagem = new Personagem();
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        
        //Incorporar todos os radio buttons no RadioGroup
        //bgGrupo.add(rbGuerreiro);
        //bgGrupo.add(rbMago);
        //bgGrupo.add(rbPaladino);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgGrupo = new javax.swing.ButtonGroup();
        txtNomePersonagem = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblClerigo = new javax.swing.JLabel();
        lblGuerreiro = new javax.swing.JLabel();
        lblMago = new javax.swing.JLabel();
        lblCavaleiro = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 11)); // NOI18N
        jLabel1.setText("Nome:");

        lblClerigo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/clerigo.png"))); // NOI18N
        lblClerigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lblClerigoKeyReleased(evt);
            }
        });

        lblGuerreiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/guerreiro.png"))); // NOI18N
        lblGuerreiro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lblGuerreiroKeyReleased(evt);
            }
        });

        lblMago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/mago.png"))); // NOI18N
        lblMago.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lblMagoKeyReleased(evt);
            }
        });

        lblCavaleiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cavaleiro.png"))); // NOI18N
        lblCavaleiro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lblCavaleiroKeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Escolha a sua classe");

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Bem-Vindo ao Jogo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCavaleiro)
                        .addGap(55, 55, 55)
                        .addComponent(lblGuerreiro)
                        .addGap(106, 106, 106))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblClerigo)
                        .addGap(55, 55, 55)
                        .addComponent(lblMago)
                        .addGap(18, 18, 18))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomePersonagem, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jLabel6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomePersonagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGuerreiro)
                    .addComponent(lblCavaleiro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMago)
                    .addComponent(lblClerigo))
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        
    private void lblCavaleiroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblCavaleiroKeyReleased
        personagem.setClasse("Cavaleiro");
        personagem.setVida(50);
        personagem.setAtaque(100);
    }//GEN-LAST:event_lblCavaleiroKeyReleased

    private void lblGuerreiroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblGuerreiroKeyReleased
        personagem.setClasse("Guerreiro");
        personagem.setVida(100);
        personagem.setAtaque(60);
    }//GEN-LAST:event_lblGuerreiroKeyReleased

    private void lblClerigoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblClerigoKeyReleased
        personagem.setClasse("Clérigo");
        personagem.setVida(100);
        personagem.setAtaque(60);
    }//GEN-LAST:event_lblClerigoKeyReleased

    private void lblMagoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblMagoKeyReleased
        personagem.setClasse("Mago");
        personagem.setVida(100);
        personagem.setAtaque(60);
    }//GEN-LAST:event_lblMagoKeyReleased
        
    private void avancar(){
        try{
            this.personagem.setNome(txtNomePersonagem.getText().trim());
            
            if(txtNomePersonagem.getText().trim().length() > 3){
                //Avançar para a tela confronto
                //Enviar os dados da Classe escolhida para a tela Confronto
                Personagem personagemEscolhido = this.personagem;

                TelaConfronto tela = new TelaConfronto(personagemEscolhido);
                tela.setVisible(true); //Mostra a tela de confronto

                //Colocar a tela atual não visivel
                this.setVisible(false);
            }else{
                CaixaDeDialogo.obterinstancia().exibirMensagem("Informe um nome com pelo menos 4 caracteres","ERRRRROOOOU",'e');
            }

        }catch(Exception ex){
            
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgGrupo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblCavaleiro;
    private javax.swing.JLabel lblClerigo;
    private javax.swing.JLabel lblGuerreiro;
    private javax.swing.JLabel lblMago;
    private javax.swing.JTextField txtNomePersonagem;
    // End of variables declaration//GEN-END:variables
}
