/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetorpg;

import ferramentas.CaixaDeDialogo;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import modelos.Personagem;

/**
 *
 * @author Jonas
 */
public class TelaPrincipal extends javax.swing.JFrame {

    Personagem personagem;
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        
        try{
            
            //ASTROLOGA
            ajustarImagem("/Users/jonasdhein/Projetos/JAVA/projeto-rpg/src/imagens/astrologa.png", lblAstrologa);        
            lblDadosAstrologa.setText("<html>Vida: 70<br/>Ataque:120</html>");
            
            //HEROINA
            ajustarImagem("/Users/jonasdhein/Projetos/JAVA/projeto-rpg/src/imagens/heroina.png", lblHeroina);     
            lblDadosHeroina.setText("<html>Vida: 100<br/>Ataque:90</html>");
            
            //GUERREIRO
            ajustarImagem("/Users/jonasdhein/Projetos/JAVA/projeto-rpg/src/imagens/guerreiro.png", lblGuerreiro);     
            lblDadosGuerreiro.setText("<html>Vida: 90<br/>Ataque:100</html>");
            
        }catch(Exception ex){
            System.out.println("Erro ao iniciar a tela");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        txtNomePersonagem = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblAstrologa = new javax.swing.JLabel();
        lblGuerreiro = new javax.swing.JLabel();
        lblHeroina = new javax.swing.JLabel();
        rbtAstrologa = new javax.swing.JRadioButton();
        rbtGuerreiro = new javax.swing.JRadioButton();
        rbtHeroina = new javax.swing.JRadioButton();
        lblDadosHeroina = new javax.swing.JLabel();
        lblDadosGuerreiro = new javax.swing.JLabel();
        lblDadosAstrologa = new javax.swing.JLabel();
        btnAvancar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 11)); // NOI18N
        jLabel1.setText("Nome de Personagem:");

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Escolha a sua classe");

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Bem-Vindo ao Jogo");

        lblAstrologa.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblAstrologa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblGuerreiro.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblGuerreiro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblHeroina.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblHeroina.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        buttonGroup1.add(rbtAstrologa);
        rbtAstrologa.setText("Astróloga");
        rbtAstrologa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtAstrologaActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtGuerreiro);
        rbtGuerreiro.setText("Guerreiro");
        rbtGuerreiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtGuerreiroActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtHeroina);
        rbtHeroina.setText("Heroína");
        rbtHeroina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtHeroinaActionPerformed(evt);
            }
        });

        lblDadosHeroina.setFont(new java.awt.Font("Roboto", 1, 11)); // NOI18N
        lblDadosHeroina.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDadosHeroina.setText("...");
        lblDadosHeroina.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lblDadosGuerreiro.setFont(new java.awt.Font("Roboto", 1, 11)); // NOI18N
        lblDadosGuerreiro.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDadosGuerreiro.setText("...");
        lblDadosGuerreiro.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lblDadosAstrologa.setFont(new java.awt.Font("Roboto", 1, 11)); // NOI18N
        lblDadosAstrologa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDadosAstrologa.setText("...");
        lblDadosAstrologa.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        btnAvancar.setText("Começar o Jogo");
        btnAvancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvancarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNomePersonagem))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAstrologa, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbtAstrologa)
                            .addComponent(lblDadosAstrologa, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHeroina, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbtHeroina)
                            .addComponent(lblDadosHeroina, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtGuerreiro)
                            .addComponent(lblGuerreiro, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDadosGuerreiro, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnAvancar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomePersonagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAstrologa, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGuerreiro, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHeroina, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtGuerreiro)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbtAstrologa)
                        .addComponent(rbtHeroina)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDadosHeroina, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDadosGuerreiro, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDadosAstrologa, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAvancar)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtAstrologaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtAstrologaActionPerformed
        //Define o personagem como Astrologa
        personagem = new Personagem();
        personagem.setClasse("Astróloga");
        personagem.setAtaque(120);
        personagem.setVida(70);
    }//GEN-LAST:event_rbtAstrologaActionPerformed

    private void rbtHeroinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtHeroinaActionPerformed
        //Define o personagem como Heroína
        personagem = new Personagem();
        personagem.setClasse("Heroína");
        personagem.setAtaque(100);
        personagem.setVida(90);
    }//GEN-LAST:event_rbtHeroinaActionPerformed

    private void rbtGuerreiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtGuerreiroActionPerformed
        //Define o personagem como Guerreiro
        personagem = new Personagem();
        personagem.setClasse("Guerreiro");
        personagem.setAtaque(90);
        personagem.setVida(100);
    }//GEN-LAST:event_rbtGuerreiroActionPerformed

    private void btnAvancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvancarActionPerformed
        //Avançar para a tela confronto
        avancar();
    }//GEN-LAST:event_btnAvancarActionPerformed
                
    private void ajustarImagem(String caminho, JLabel label){
        try{
            
            ImageIcon imageIcon = new ImageIcon(caminho);
            Image img = imageIcon.getImage();
            Image imgScale = img.getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon scaledimageIcon = new ImageIcon(imgScale);
            label.setIcon(scaledimageIcon);
            
        }catch(Exception ex){
            
        }
    }
    
    private void avancar(){
        try{
            this.personagem.setNome(txtNomePersonagem.getText().trim());
            
            if(txtNomePersonagem.getText().trim().length() > 3){
                
                //Enviar os dados da Classe escolhida para a tela Confronto
                TelaConfronto tela = new TelaConfronto(this.personagem);
                tela.setVisible(true); //Mostra a tela de confronto

                //Colocar a tela atual não visivel
                this.setVisible(false);
            }else{
                CaixaDeDialogo.obterinstancia().exibirMensagem("Informe um nome com pelo menos 4 caracteres","ERRRRROOOOU",'e');
            }

        }catch(Exception ex){
            
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvancar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblAstrologa;
    private javax.swing.JLabel lblDadosAstrologa;
    private javax.swing.JLabel lblDadosGuerreiro;
    private javax.swing.JLabel lblDadosHeroina;
    private javax.swing.JLabel lblGuerreiro;
    private javax.swing.JLabel lblHeroina;
    private javax.swing.JRadioButton rbtAstrologa;
    private javax.swing.JRadioButton rbtGuerreiro;
    private javax.swing.JRadioButton rbtHeroina;
    private javax.swing.JTextField txtNomePersonagem;
    // End of variables declaration//GEN-END:variables
}
